name: Release Codepush Build and Deploy

on: 
  push:
    branches:
      - 'release/codepush_**'
jobs:
  codepush-android-build-deploy:
      name: Codepush Android Build and Deploy
      runs-on: ubuntu-latest
      env:
        ACTIONS_OS_NAME: "linux"
        NODE_OPTIONS: --max_old_space_size=8192
        CODEPUSH_KEY_PASSWORD: ${{ secrets.CODEPUSH_API_TOKEN }}
        timeout-minutes: 120
      steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 50
      - uses: geertvdc/setup-hub@master
      - name: Configure Git
        run: |
          git config --local user.email "vijay.jeyaraman@cognizant.com"
          git config --local user.name "Vijay Actions"
      - name: create PR
        run: node ./devScripts/createDiffPR.js

  
